name: ECS THUMBNAILS CI

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./deployment/thumbnails_api

    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 1
    
        - uses: hashicorp/setup-terraform@v2

        - name: init
          run: terraform init

        - name: validate
          run: terraform validate

        - name: plan
          run: terraform plan

        - name: apply or destroy
          run: |
            terraform apply -var 'container_image=${{ vars.PYTHUMBNAILSCAPSTONE_IMAGE_VER_LATEST }}' -auto-approve
          shell: bash
