name: Update container image

on:
  workflow_dispatch:
  
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  CI:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./testing

    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 1
            ref: main
    
        - uses: hashicorp/setup-terraform@v2

        - name: init
          run: terraform init

        - name: validate
          run: terraform validate

        - name: plan
          run: terraform plan

        - name: apply
          run: terraform apply -var 'container_image=${{ vars.PYDBCAPSTONE_IMAGE_VER_LATEST }}' -auto-approve
